import customtkinter

customtkinter.set_appearance_mode("dark")
customtkinter.set_default_color_theme("dark-blue")    
root = customtkinter.CTk()
root.geometry("400x450")
frame = customtkinter.CTkFrame(master = root)
frame.pack(pady = 20, padx = 60, fill = "both", expand = True)
file = open("./tasks.txt", "r")
tasksNum = file.read()
file.close()
file = open("./pomodoros.txt", "r")
pomodoros = file.read()
file.close()
title = customtkinter.CTkLabel(master = frame, text = "Weekly Report", font = ("Roboto", 40))
label1 = customtkinter.CTkLabel(master = frame, text = "Tasks accomplished this week: " + tasksNum, font = ("Roboto", 16))
label2 = customtkinter.CTkLabel(master = frame, text = "Pomodoros accomplished this week: " + pomodoros, font = ("Roboto", 15))
title.place(relx = 0.045, rely = 0.1)
label1.place(relx = 0.075, rely = 0.45)
label2.place(relx = 0.04, rely = 0.50)
root.mainloop()